name: install ASDF tools from repo
description: Install ASDF and tools defined in .tool-versions and .tool-repos if they are present in the repository.
runs:
  using: "composite"
  steps:
    - name: Install ASDF
      uses: asdf-vm/actions/setup@v3

    - name: Install ASDF plugins
      run: |
        if [ -f .tool-repos ]; then
          cat .tool-repos | while read tool || [[ -n $tool ]]; do
            PLUGIN=$(echo $tool | cut -d ' ' -f 1)
            echo "Plugin: $PLUGIN"
            REPO=$(echo $tool | cut -d ' ' -f 2)
            echo "URL: $REPO"
            asdf plugin add $PLUGIN $REPO
          done
        fi
      shell: bash

    - name: Install ASDF tools
      run: |
        if [ -f .tool-versions ]; then
          awk -F'[ #]' '$NF ~ /https/ {system("asdf plugin add " $1 " " $NF)} $1 ~ /./ {system("asdf plugin add " $1 "; asdf install " $1 " " $2)}' ./.tool-versions
        fi
      shell: bash
